language: node_js
node_js:
  - stable
before_script:
   - npm install -g @angular/cli
script:
  - cd town
  - npm install
  - ng build --prod --bh /projet2-web/town
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ce9649ef678ace2c5d9ee4f45ec4f32609f66f41
  keep-history: true
  on:
branch: master