language: node_js
node_js:
  - stable
before_script:
   - npm install -g @angular/cli
script:
  - npm install
  - npm run prod
  - ng build --prod --bh /projet2-web
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
branch: master